"""
Entity definitions: maps internal entity names to qbXML query names,
sync order, and configuration.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import NamedTuple


@dataclass
class EntityDef:
    """Definition for a syncable QB entity."""
    name: str                    # Internal name (matches companies.yaml)
    query_rq: str                # qbXML request element name
    query_rs: str                # qbXML response element name
    ret_element: str             # The "Ret" element in response (e.g., CustomerRet)
    pk_field: str                # Primary key field: "ListID" or "TxnID"
    is_transaction: bool         # False = list object, True = transaction
    supports_iterator: bool      # Whether iterator is supported
    supports_modified_filter: bool  # Whether ModifiedDateRangeFilter works
    supports_txn_date_filter: bool  # Whether TxnDateRangeFilter works
    max_returned: int            # Default batch size
    sync_priority: int           # Lower = sync first


# Complete entity registry in sync order
ENTITY_REGISTRY: list[EntityDef] = [
    # ========== Phase 1: Reference Data (Lists) ==========
    EntityDef(
        name="accounts",
        query_rq="AccountQueryRq",
        query_rs="AccountQueryRs",
        ret_element="AccountRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=200,
        sync_priority=10,
    ),
    EntityDef(
        name="classes",
        query_rq="ClassQueryRq",
        query_rs="ClassQueryRs",
        ret_element="ClassRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=200,
        sync_priority=20,
    ),
    EntityDef(
        name="sales_tax_codes",
        query_rq="SalesTaxCodeQueryRq",
        query_rs="SalesTaxCodeQueryRs",
        ret_element="SalesTaxCodeRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=200,
        sync_priority=30,
    ),
    EntityDef(
        name="payment_methods",
        query_rq="PaymentMethodQueryRq",
        query_rs="PaymentMethodQueryRs",
        ret_element="PaymentMethodRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=200,
        sync_priority=40,
    ),
    EntityDef(
        name="ship_methods",
        query_rq="ShipMethodQueryRq",
        query_rs="ShipMethodQueryRs",
        ret_element="ShipMethodRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=200,
        sync_priority=50,
    ),
    EntityDef(
        name="terms",
        query_rq="StandardTermsQueryRq",
        query_rs="StandardTermsQueryRs",
        ret_element="StandardTermsRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=200,
        sync_priority=60,
    ),
    EntityDef(
        name="customers",
        query_rq="CustomerQueryRq",
        query_rs="CustomerQueryRs",
        ret_element="CustomerRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=100,
        sync_priority=100,
    ),
    EntityDef(
        name="vendors",
        query_rq="VendorQueryRq",
        query_rs="VendorQueryRs",
        ret_element="VendorRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=100,
        sync_priority=110,
    ),
    EntityDef(
        name="employees",
        query_rq="EmployeeQueryRq",
        query_rs="EmployeeQueryRs",
        ret_element="EmployeeRet",
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=100,
        sync_priority=120,
    ),
    EntityDef(
        name="items",
        query_rq="ItemQueryRq",
        query_rs="ItemQueryRs",
        ret_element=None,  # ItemQueryRs contains mixed types: ItemServiceRet, ItemInventoryRet, etc.
        pk_field="ListID",
        is_transaction=False,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=False,
        max_returned=100,
        sync_priority=130,
    ),
    # ========== Phase 2: Transactions ==========
    EntityDef(
        name="purchase_orders",
        query_rq="PurchaseOrderQueryRq",
        query_rs="PurchaseOrderQueryRs",
        ret_element="PurchaseOrderRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=200,
    ),
    EntityDef(
        name="bills",
        query_rq="BillQueryRq",
        query_rs="BillQueryRs",
        ret_element="BillRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=210,
    ),
    EntityDef(
        name="bill_payments",
        query_rq="BillPaymentCheckQueryRq",
        query_rs="BillPaymentCheckQueryRs",
        ret_element="BillPaymentCheckRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=220,
    ),
    EntityDef(
        name="vendor_credits",
        query_rq="VendorCreditQueryRq",
        query_rs="VendorCreditQueryRs",
        ret_element="VendorCreditRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=230,
    ),
    EntityDef(
        name="estimates",
        query_rq="EstimateQueryRq",
        query_rs="EstimateQueryRs",
        ret_element="EstimateRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=240,
    ),
    EntityDef(
        name="sales_orders",
        query_rq="SalesOrderQueryRq",
        query_rs="SalesOrderQueryRs",
        ret_element="SalesOrderRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=250,
    ),
    EntityDef(
        name="invoices",
        query_rq="InvoiceQueryRq",
        query_rs="InvoiceQueryRs",
        ret_element="InvoiceRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=50,
        sync_priority=300,
    ),
    EntityDef(
        name="sales_receipts",
        query_rq="SalesReceiptQueryRq",
        query_rs="SalesReceiptQueryRs",
        ret_element="SalesReceiptRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=50,
        sync_priority=310,
    ),
    EntityDef(
        name="credit_memos",
        query_rq="CreditMemoQueryRq",
        query_rs="CreditMemoQueryRs",
        ret_element="CreditMemoRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=50,
        sync_priority=320,
    ),
    EntityDef(
        name="receive_payments",
        query_rq="ReceivePaymentQueryRq",
        query_rs="ReceivePaymentQueryRs",
        ret_element="ReceivePaymentRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=330,
    ),
    EntityDef(
        name="deposits",
        query_rq="DepositQueryRq",
        query_rs="DepositQueryRs",
        ret_element="DepositRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=340,
    ),
    EntityDef(
        name="checks",
        query_rq="CheckQueryRq",
        query_rs="CheckQueryRs",
        ret_element="CheckRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=350,
    ),
    EntityDef(
        name="credit_card_charges",
        query_rq="CreditCardChargeQueryRq",
        query_rs="CreditCardChargeQueryRs",
        ret_element="CreditCardChargeRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=360,
    ),
    EntityDef(
        name="credit_card_credits",
        query_rq="CreditCardCreditQueryRq",
        query_rs="CreditCardCreditQueryRs",
        ret_element="CreditCardCreditRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=370,
    ),
    EntityDef(
        name="journal_entries",
        query_rq="JournalEntryQueryRq",
        query_rs="JournalEntryQueryRs",
        ret_element="JournalEntryRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=50,
        sync_priority=380,
    ),
    EntityDef(
        name="transfers",
        query_rq="TransferQueryRq",
        query_rs="TransferQueryRs",
        ret_element="TransferRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=390,
    ),
    EntityDef(
        name="inventory_adjustments",
        query_rq="InventoryAdjustmentQueryRq",
        query_rs="InventoryAdjustmentQueryRs",
        ret_element="InventoryAdjustmentRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=100,
        sync_priority=400,
    ),
    EntityDef(
        name="time_tracking",
        query_rq="TimeTrackingQueryRq",
        query_rs="TimeTrackingQueryRs",
        ret_element="TimeTrackingRet",
        pk_field="TxnID",
        is_transaction=True,
        supports_iterator=True,
        supports_modified_filter=True,
        supports_txn_date_filter=True,
        max_returned=200,
        sync_priority=410,
    ),
]

# Index by name for quick lookup
ENTITY_BY_NAME: dict[str, EntityDef] = {e.name: e for e in ENTITY_REGISTRY}


def get_entity(name: str) -> EntityDef:
    if name not in ENTITY_BY_NAME:
        raise KeyError(f"Unknown entity: {name}")
    return ENTITY_BY_NAME[name]


def get_entities_for_company(enabled_names: list[str]) -> list[EntityDef]:
    """Return EntityDef list in sync_priority order for enabled entities."""
    result = []
    for name in enabled_names:
        if name in ENTITY_BY_NAME:
            result.append(ENTITY_BY_NAME[name])
        # Silently skip unknown entity names (e.g., future additions)
    result.sort(key=lambda e: e.sync_priority)
    return result
